---
env:
  node: true,
  browser: false
parserOptions:
  ecmaVersion: 8
  sourceType: module
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  quotes:
    - error
    - single
  semi:
    - error
    - always