version: 2
jobs:
  prepare:
    working_directory: ~/app
    docker:
        - image: circleci/node:8.9
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
      - checkout
      - run: make install
      - save_cache:
          paths:
            - .
          key: build-{{ .Revision }}
  lint:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
      - restore_cache:
          keys:
            - build-{{ .Revision }}
      - run: make lint
  test:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
      - restore_cache:
          keys:
            - build-{{ .Revision }}
      - run: make test
  compile:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
      - restore_cache:
          keys:
            - build-{{ .Revision }}
      - run: make compile
      - save_cache:
          paths:
            - .
          key: build-{{ .Revision }}
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
      - restore_cache:
          keys:
            - build-{{ .Revision }}
      - run: |
          make build
          docker tag local/mow-it $DOCKER_USER/mow-it:$CIRCLE_SHA1
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push $DOCKER_USER/mow-it:$CIRCLE_SHA1
  release:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
      - restore_cache:
          keys:
            - bootstrap-{{ .Revision }}
      - run: |
          VERSION=$(echo "console.log(require('./package.json').version)" >> version.js && node version.js)
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker pull $DOCKER_USER/mow-it:$CIRCLE_SHA1
          docker tag $DOCKER_USER/mow-it:$CIRCLE_SHA1 $DOCKER_USER/mow-it:latest
          docker push $DOCKER_USER/mow-it:latest
          docker tag $DOCKER_USER/mow-it:$CIRCLE_SHA1 $DOCKER_USER/mow-it:$VERSION
          docker push $DOCKER_USER/mow-it:$VERSION

workflows:
  version: 2
  commit:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      - compile:
          requires:
            - lint
            - test
      - build:
          requires:
            - compile
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
