version: 2
jobs:
  prepare:
    working_directory: ~/app
    docker:
        - image: circleci/node:8.9
    steps:
      - checkout
      - run: npm install
      - save_cache:
          paths:
            - .
          key: bootstrap
  test:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9
    steps:
      - restore_cache:
          keys:
            - bootstrap
      - run: make test
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
      - restore_cache:
          keys:
            - bootstrap
      - run: docker build -t thomrick/mow-it:${CIRCLE_SHA1} .
  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
      - run: docker image ls


workflows:
  version: 2
  commit:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build